version: '3'
services:
  web:
    build: apache
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./app:/app
      - ./apache/certificados:/certificados
      - ./apache/configuracion.conf:/etc/apache2/sites-enabled/configuracion.conf
      
  basededatos:
    image: mysql:latest
    volumes:
      - ./database/backup:/docker-entrypoint-initdb.b
      - ./database/backup:/database/backup
      - datos:/var/lib/mysql
    env_file:
      - ./apache/dev-conf/.env.dev
volumes:
  datos:
