version: '3'
services:
  web:
    build: apache
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./app:/app
      - ./apache/certificados:/certificados
      - ./apache/configuracion.conf:/etc/apache2/sites-enabled/configuracion.conf
    env_file:
      - ./apache/prod-conf/.env.prod
